### ISSUE TITLE
Versioning the scripts

### ISSUE THREAD

**Issue by SnarkBoojum** [mathiasbynens/node-unicode-data#21]
Hi,

I plan on packaging node-unicode-7.0.0 in debian ; for that I would need to use sources, ie : use the script to generate the binary packages containing the data.

Unfortunately, you didn't tag any release of these sources : could you please do?

Thanks,

Snark on #debian-js

**Comment by mathiasbynens** [comment]
Unicode v7.0.0 data was added here: https://github.com/mathiasbynens/node-unicode-data/commit/43e222ae4a15d0d2e687f2e00764e15c24b08822 This commit corresponds to https://www.npmjs.com/package/unicode-7.0.0 v0.1.5.

Each individual data package (e.g. `unicode-3.1.0`, `unicode-7.0.0`, etc.) is versioned following https://github.com/mathiasbynens/node-unicode-data/blob/2ead4522aa1564e8c569189e7fe8ceaf3d7b99d7/templates/package.json#L3. You can track changes that file’s history to see which scripts were used to generate the data for each version.

The only release of unicode-7.0.0 has been v0.1.5 which corresponds to the commit I pointed to.

Does that help?

For this repository tagging is not used, as it wouldn’t really work IMHO. For example, if I had tagged a certain commit as v0.1.5 in this repo, it wouldn’t accurately reflect this project’s history. Consider this: if Unicode v9.0.0 gets released, but there are no changes in the script that generates the data until then, then v0.1.5 will be the first release of unicode-9.0.0 on npm. It wouldn’t make sense to bump the version number for all data packages since their data won’t have changed.

**Comment by SnarkBoojum** [comment]
I don't get it : if a new Unicode version comes out, you'll need to update the script for it, won't you? Then it will be logical to push the script version up.

If you don't want to use the script to push new versions of the previous Unicode versions, that's ok : what's the problem with having unicode-7.0.0 created by script version 0.1.5 and unicode-8.0.0 created by script version 0.1.6 ?

My point in this issue was that I lack the tags to know when the script changes.

**Comment by mathiasbynens** [comment]
> I don't get it : if a new Unicode version comes out, you'll need to update the script for it, won't you? Then it will be logical to push the script version up.

There’s a difference between the individual data packages (for each Unicode version) and the script that generates them. You’re conflating the two. If the data in a data package doesn’t change, the version number shouldn’t change either.

You can look at the history of `templates/package.json` to achieve your goal.
