### ISSUE TITLE
Add JSON and/or CSV lists

### ISSUE THREAD

**Issue by isiahmeadows** [mathiasbynens/node-unicode-data#52]
It'd be nice if I could read a form of the file that I could parse without having to commit it to the module cache. I have a need to handle several categories at once to combine them,\* and the fact they can take upwards of several megabytes exploded makes it easy to leak out of the module cache.

\* I know this sounds a *lot* like what Regenerator does, but I avoid the dependency because I need access to the raw ranges, and it's just easier to hand-roll it all myself for my particular use case.

**Comment by mathiasbynens** [comment]
Can you share more details about your use case? Since the data packages are supposed to be used *at build time* (and never at run-time) memory usage shouldn’t really matter.

**Comment by isiahmeadows** [comment]
In my immediate case, I have to combine about 7 major categories (~140K total code points, including duplicates) and merge them for two separate applications (Regenerator + manual merging for Unicode tester). It is in fact at build-time, but I have a few machines that aren't 16GB. It's low-priority for me and a pure nice-to-have, but I could see other cases where it might get more extreme.

I'm also working on a compiler where I'll need the entire database potentially, and if I can't get this, I'll have to fork the project later to just build what I need. (It might be better for me to just fork the project and do my own thing in native anyways, since I have some specialized requirements here.)

**Comment by mathiasbynens** [comment]
I think the best way forward for this specific use case (other than doing it natively) would be to build an intermediary package e.g. `isiah-unicode-data` that depends on e.g. `unicode-11.0.0`, runs a build script, and then produces the data files in the format you want. Your main project then depends on `isiah-unicode-data` rather than `unicode-11.0.0` directly. To update the data later, you update `isiah-unicode-data`’s `unicode-11.0.0` dependency, re-run the build script, publish a new `isiah-unicode-data` version, and then update the `isiah-unicode-data` dependency in your main project.

**Comment by isiahmeadows** [comment]
@mathiasbynens Understandable, and by the point I actually need to fork the project, I might end up simply adapting the code and internalizing it within the compiler, since it'll be so intertwined with it. (I'm not 100% sure it'll be written in JS to begin with.) My particular use case is good enough for now, and since this is a very low-priority thing for me currently, I'm going to close this.

**Comment by mathiasbynens** [comment]
With [my earlier suggestion](https://github.com/mathiasbynens/node-unicode-data/issues/52#issuecomment-397564727) you wouldn’t be forking the project.
